
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TooOmy
 */
public class VmGui extends javax.swing.JFrame {
    Integer R;
    Boolean C;
    Integer IC;
    Integer PLR;
    ArrayList Atmintis_Arr;
    String Console;
    String busena;
    /**
     * Creates new form VmGui
     */
    public VmGui(VM vm) {
        this.R = vm.R;
        this.C = vm.C;
        this.IC = vm.IC;
        this.PLR = vm.PLR;
        this.busena = vm.Busena;
        this.Atmintis_Arr = vm.Atmintis_Arr;
        initComponents();
        R_R_V.setText(Integer.toBinaryString(R));
        R_IC_V.setText(Integer.toBinaryString(IC));
        R_C_V.setText(Boolean.toString(C));
        R_R_V1.setText(Integer.toBinaryString(PLR));
        R_Busena_V.setText(busena);
        for (int i = 0; i<Atmintis_Arr.size();i++)
        Atmintis_List_V.add(i + ": " + Atmintis_Arr.get(i), i);
        Console_Read_V.append("cia bus konsoles tekstas");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Atmintis_Jpanel = new javax.swing.JPanel();
        Atmintis_text = new javax.swing.JLabel();
        Atmintis_List_V = new java.awt.List();
        Registrai_Jpanel = new javax.swing.JPanel();
        Registrai_text = new javax.swing.JLabel();
        R_R_Text = new javax.swing.JLabel();
        R_IC_Text = new javax.swing.JLabel();
        R_C_Text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        R_R_V = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        R_IC_V = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        R_C_V = new javax.swing.JTextPane();
        R_PLR_Text = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        R_R_V1 = new javax.swing.JTextPane();
        R_Busena_Text = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        R_Busena_V = new javax.swing.JTextPane();
        Console_Jpanel = new javax.swing.JPanel();
        Console_Read_V = new java.awt.TextArea();
        Console_Write_V = new java.awt.TextField();
        Ikelti_Programa_B = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atmintis_text.setText("Atmintis:");

        Atmintis_List_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atmintis_List_VActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Atmintis_JpanelLayout = new javax.swing.GroupLayout(Atmintis_Jpanel);
        Atmintis_Jpanel.setLayout(Atmintis_JpanelLayout);
        Atmintis_JpanelLayout.setHorizontalGroup(
            Atmintis_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Atmintis_JpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Atmintis_text, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(Atmintis_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atmintis_List_V, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Atmintis_JpanelLayout.setVerticalGroup(
            Atmintis_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Atmintis_JpanelLayout.createSequentialGroup()
                .addComponent(Atmintis_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Atmintis_List_V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Registrai_text.setText("Registrai:");

        R_R_Text.setText("R:");

        R_IC_Text.setText("IC:");

        R_C_Text.setText("C:");

        R_R_V.setEditable(false);
        jScrollPane1.setViewportView(R_R_V);

        R_IC_V.setEditable(false);
        jScrollPane2.setViewportView(R_IC_V);

        R_C_V.setEditable(false);
        jScrollPane3.setViewportView(R_C_V);

        R_PLR_Text.setText("PLR:");

        R_R_V1.setEditable(false);
        jScrollPane4.setViewportView(R_R_V1);

        R_Busena_Text.setText("Busena:");

        R_Busena_V.setEditable(false);
        jScrollPane5.setViewportView(R_Busena_V);

        javax.swing.GroupLayout Registrai_JpanelLayout = new javax.swing.GroupLayout(Registrai_Jpanel);
        Registrai_Jpanel.setLayout(Registrai_JpanelLayout);
        Registrai_JpanelLayout.setHorizontalGroup(
            Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Registrai_text)
                    .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                        .addComponent(R_IC_Text)
                        .addGap(18, 18, 18)
                        .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)))
                    .addComponent(R_C_Text)
                    .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                        .addComponent(R_R_Text)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                        .addComponent(R_PLR_Text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                        .addComponent(R_Busena_Text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Registrai_JpanelLayout.setVerticalGroup(
            Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                .addComponent(Registrai_text)
                .addGap(18, 18, 18)
                .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                        .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R_R_Text))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Registrai_JpanelLayout.createSequentialGroup()
                                .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R_IC_Text)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_PLR_Text))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Registrai_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R_C_Text)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(R_Busena_Text)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Console_Read_V.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Console_Read_V.setEditable(false);

        Console_Write_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Console_Write_VActionPerformed(evt);
            }
        });

        Ikelti_Programa_B.setText("Ikelti programa");
        Ikelti_Programa_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ikelti_Programa_BActionPerformed(evt);
            }
        });

        jButton1.setText("Vykdyti programa");

        jButton2.setText("Vykdyti 1 žingsni");

        jButton3.setText("Perkrauti procesoriu");

        javax.swing.GroupLayout Console_JpanelLayout = new javax.swing.GroupLayout(Console_Jpanel);
        Console_Jpanel.setLayout(Console_JpanelLayout);
        Console_JpanelLayout.setHorizontalGroup(
            Console_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Console_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Console_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Console_Read_V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Console_Write_V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Console_JpanelLayout.createSequentialGroup()
                        .addComponent(Ikelti_Programa_B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Console_JpanelLayout.setVerticalGroup(
            Console_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Console_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Console_Read_V, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Console_Write_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Console_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ikelti_Programa_B)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Console_Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Registrai_Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Atmintis_Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Registrai_Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Console_Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Atmintis_Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Console_Write_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Console_Write_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Console_Write_VActionPerformed

    private void Ikelti_Programa_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ikelti_Programa_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ikelti_Programa_BActionPerformed

    private void Atmintis_List_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atmintis_List_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Atmintis_List_VActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form //*/
    /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VmGui().setVisible(true);
            }
        });
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atmintis_Jpanel;
    private java.awt.List Atmintis_List_V;
    private javax.swing.JLabel Atmintis_text;
    private javax.swing.JPanel Console_Jpanel;
    private java.awt.TextArea Console_Read_V;
    private java.awt.TextField Console_Write_V;
    private javax.swing.JButton Ikelti_Programa_B;
    private javax.swing.JLabel R_Busena_Text;
    private javax.swing.JTextPane R_Busena_V;
    private javax.swing.JLabel R_C_Text;
    private javax.swing.JTextPane R_C_V;
    private javax.swing.JLabel R_IC_Text;
    private javax.swing.JTextPane R_IC_V;
    private javax.swing.JLabel R_PLR_Text;
    private javax.swing.JLabel R_R_Text;
    private javax.swing.JTextPane R_R_V;
    private javax.swing.JTextPane R_R_V1;
    private javax.swing.JPanel Registrai_Jpanel;
    private javax.swing.JLabel Registrai_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
